displayName: ReplaceBody Plugin
type: middleware

import: github.com/rikkartx/replacebody

summary: '[ReplaceBody] Replace Original Request By Response From Specified Address'

testData:
  Address: https://httpbin.org/robots.txt
  Method: GET
